[
    CustomConstructor,
    ImplementationLacksVTable
] interface CContext {
    // Functions for generating kernels.
    [Custom] CKernel compileKernel(DOMString source, DOMString kernelName, [Default=NullString] optional DOMString options);

    // Debugging the build process.
    readonly attribute DOMString buildLog;

    // Functions for mapping data.
    [Custom] CData mapData(ArrayBufferView source);
    [Custom] CData cloneData(ArrayBufferView source);
    [Custom] CData allocateData(ArrayBufferView templ, [Default=Undefined] optional unsigned long length);
    [Custom] CData allocateData2(CData templ, [Default=Undefined] optional unsigned long length);
    [Custom] boolean canBeMapped(ArrayBufferView source);

    // Profiling support.
    readonly attribute unsigned long long lastExecutionTime;
    readonly attribute unsigned long long lastRoundTripTime;

    // device property queries
    readonly attribute DOMString extensions;

    // Canvas writing support.
    [Custom] void writeToContext2D(CanvasRenderingContext2D ctx, ArrayBufferView source, long width, long height);

    // Aligning support.
    readonly attribute unsigned long alignmentSize;
    [Custom] unsigned long getAlignmentOffset(ArrayBufferView source);
};
