[
    CustomConstructor,
    ImplementationLacksVTable
] interface CKernel {
    boolean setArgument(unsigned long number, CData argument);
    [Custom] boolean setScalarArgument(unsigned long number, any argument, boolean isInteger, boolean highPrecision);
    [Custom] unsigned long run(unsigned long rank, Array shape, [Default=Undefined] optional Array tile);
     
    [CustomGetter] readonly attribute unsigned long numberOfArgs;
};
