module rivertrail {

    interface [
        V8CustomConstructor,
        ConstructorParameters=1
    ] CKernel {
        boolean setArgument( in unsigned long number, in CData argument);
        [V8Custom] boolean setScalarArgument( in unsigned long number, in DOMObject argument, in DOMObject isInteger, in DOMObject highPrecision);
        [V8Custom] unsigned long run( in unsigned long rank, in Array shape, in [Optional=DefaultIsUndefined] Array tile);
        
        readonly attribute [V8CustomGetter] unsigned long numberOfArgs;
    };
}
